import path from "node:path";
import { fileURLToPath } from "node:url";

import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { Client, Pool } from "pg";

import { applyAccessEventsBytesOnline, validateDeferredConstraints } from "./online-constraints";

export const MIGRATIONS_FOLDER = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../drizzle",
);

/**
 * Pinned search path of the migration session (security re-review N2): only `public`, which only
 * the owner can create objects in (`pg_catalog` is always searched first implicitly). Listing
 * `pg_catalog` explicitly first would make it the creation schema of the unqualified
 * `CREATE TABLE` statements generated by drizzle-kit.
 */
export const MIGRATION_SEARCH_PATH = "public";

/**
 * Advisory lock key of `migrate` (per database: advisory locks are scoped to the current database).
 * Arbitrary constant: the ASCII bytes of "DBmigrat" as a big-endian 64-bit integer.
 */
export const MIGRATION_LOCK_KEY = "4918614042516545908";

export class PgbossOwnerError extends Error {
  override name = "PgbossOwnerError";
}

/**
 * Pre-flight of every migrate run, same check as migration `0009_pgboss_owner_guard.sql` (which
 * only runs once): refuses when schema `pgboss` exists and is owned by a role other than the
 * migration role, before any migration SQL runs. Role names are not secrets.
 */
export async function assertPgbossOwnership(pool: Pool): Promise<void> {
  const { rows } = await pool.query<{ schema_owner: string; migration_role: string }>(
    `select pg_catalog.pg_get_userbyid(n.nspowner) as schema_owner, current_user as migration_role
       from pg_catalog.pg_namespace n where n.nspname = 'pgboss'`,
  );
  const row = rows[0];
  if (row && row.schema_owner !== row.migration_role) {
    throw new PgbossOwnerError(
      `schema pgboss is owned by role ${row.schema_owner}, not by the migration role ${row.migration_role}: ` +
        "as a superuser, ALTER SCHEMA pgboss OWNER TO the migration (owner) role after checking the schema for planted objects " +
        '(console/README.md, "Database roles")',
    );
  }
}

/**
 * Applies the committed migrations with a dedicated pool, as the role of `url` (the owner), after
 * the `pgboss` ownership pre-flight. Around drizzle's migrator (one transaction for all pending
 * migrations), the lock-friendly constraint steps of `online-constraints.ts`: `0027` applied with
 * its CHECK `NOT VALID` then validated on its own when upgrading an install at `0026`, and the
 * validation of any listed constraint still `NOT VALID`. `migrationsFolder`: tests only.
 *
 * Concurrent `migrate` runs are serialized (security review L1): a session-level advisory lock is
 * held on a dedicated connection for the whole run (pre-flights, migrator, deferred validations),
 * so a second run waits, then finds nothing pending. The work itself runs on the pool's connection.
 */
export async function runMigrations(url: string, migrationsFolder: string = MIGRATIONS_FOLDER): Promise<void> {
  const pool = new Pool({
    connectionString: url,
    application_name: "databastion-migrate",
    max: 1,
    options: `-c search_path=${MIGRATION_SEARCH_PATH}`,
  });
  const lock = new Client({ connectionString: url, application_name: "databastion-migrate-lock" });
  try {
    await lock.connect();
    await lock.query("select pg_advisory_lock($1::bigint)", [MIGRATION_LOCK_KEY]);
    try {
      await assertPgbossOwnership(pool);
      await applyAccessEventsBytesOnline(pool, migrationsFolder);
      await migrate(drizzle(pool), { migrationsFolder });
      await validateDeferredConstraints(pool);
    } finally {
      await lock.query("select pg_advisory_unlock($1::bigint)", [MIGRATION_LOCK_KEY]).catch(() => undefined);
    }
  } finally {
    await lock.end().catch(() => undefined);
    await pool.end();
  }
}
