import path from "node:path";
import { fileURLToPath } from "node:url";

import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { Pool } from "pg";

export const MIGRATIONS_FOLDER = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../drizzle",
);

/**
 * Pinned search path of the migration session (security re-review N2): only `public`, which only
 * the owner can create objects in (`pg_catalog` is always searched first implicitly). Listing
 * `pg_catalog` explicitly first would make it the creation schema of the unqualified
 * `CREATE TABLE` statements generated by drizzle-kit.
 */
export const MIGRATION_SEARCH_PATH = "public";

/** Applies the committed migrations with a dedicated pool, as the role of `url` (the owner). */
export async function runMigrations(url: string): Promise<void> {
  const pool = new Pool({
    connectionString: url,
    application_name: "databastion-migrate",
    max: 1,
    options: `-c search_path=${MIGRATION_SEARCH_PATH}`,
  });
  try {
    await migrate(drizzle(pool), { migrationsFolder: MIGRATIONS_FOLDER });
  } finally {
    await pool.end();
  }
}
