#!/usr/bin/env python3
"""Scaled seed and workload scripts of the load / database impact harness (e2e/load/run.sh).

Nothing produced here is committed: run.sh calls this module at run time and feeds its output to
the targets (SQL / JavaScript on stdin, as the superuser inside each target container) and to the
workload clients (pgbench scripts, a sysbench Lua script).

The data is synthetic and deterministic (a function of the table index and the row id): e-mail
addresses under example.* domains, French mobile numbers, French IBANs with valid ISO 7064 check
digits, plus non-sensitive columns. It is generated by the database server itself
(`generate_series`, MariaDB's `seq_1_to_N` Sequence engine tables, a mongosh loop), so no large
file crosses the Docker socket.

Table plan: `tables` tables share `total_rows` rows; every `large_every`-th table weighs
`large_factor` times a small one (a few large tables, many small ones, as in a real schema). Kinds
cycle over `contact` (e-mail, phone), `billing` (IBAN, amount), `plain` (no sensitive column) and
`mixed` (e-mail, phone, IBAN).

Usage:
  seed.py plan     --tables N --rows N              one "<index> <name> <rows> <kind>" per line
  seed.py pg       --tables N --rows N              SQL for target-pg (psql, superuser, db shop)
  seed.py mariadb  --tables N --rows N              SQL for target-mariadb (mariadb, root)
  seed.py mongo    --tables N --rows N              JavaScript for mongosh (`c`: a root connection)
  seed.py pgbench  --tables N --rows N --out DIR    one pgbench script per workload table (pg_tNNN.sql)
  seed.py sysbench --tables N --rows N              sysbench Lua script (MariaDB point selects)
  (--workload-tables N, default 40: the workload reads the first N tables of the plan)
"""

from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass

KINDS = ("contact", "billing", "plain", "mixed")
PG_SCHEMAS = ("load_a", "load_b", "load_c", "load_d")
# The agent's MariaDB account (ADR-0018 minimal variant) reads `support` only: the load tables go
# there. MongoDB: the agent's role reads `app` only.
MARIADB_DATABASE = "support"
MONGO_DATABASE = "app"
FIRST_NAMES = (
    "camille", "louis", "lea", "hugo", "chloe", "lucas", "manon", "jules", "ines", "adam",
    "sarah", "gabriel", "emma", "arthur", "jade", "nathan", "alice", "paul", "lina", "victor",
)
LAST_NAMES = (
    "martin", "bernard", "dubois", "thomas", "robert", "richard", "petit", "durand", "leroy",
    "moreau", "simon", "laurent", "lefebvre", "michel", "garcia", "david", "bertrand", "roux",
    "vincent", "fournier",
)
MAIL_DOMAINS = ("mail.example.org", "post.example.net", "inbox.example.com", "courrier.example.fr")
STATUSES = ("open", "closed", "pending", "archived")
# French BBAN: bank code, branch code (the table index), 11-digit account (the row id), 2-digit key.
BANK_CODE = "30004"

MIN_ROWS = 100
MAX_TABLES = 999
# pgbench accepts at most 128 scripts: the workload reads the first tables of the plan (its "hot" set).
MAX_WORKLOAD_TABLES = 100


@dataclass(frozen=True)
class Table:
    index: int  # 1-based
    rows: int
    kind: str

    @property
    def tag(self) -> str:
        return f"{self.index:03d}"

    @property
    def pg_schema(self) -> str:
        return PG_SCHEMAS[(self.index - 1) % len(PG_SCHEMAS)]

    @property
    def pg_name(self) -> str:
        return f"{self.pg_schema}.t{self.tag}"

    @property
    def mariadb_name(self) -> str:
        return f"load_t{self.tag}"

    @property
    def mongo_name(self) -> str:
        return f"load_c{self.tag}"

    @property
    def columns(self) -> tuple[str, ...]:
        return {
            "contact": ("email", "phone"),
            "billing": ("iban", "amount"),
            "plain": ("amount", "quantity"),
            "mixed": ("email", "phone", "iban"),
        }[self.kind]


def plan(tables: int, total_rows: int, large_every: int = 10, large_factor: int = 20) -> list[Table]:
    """Splits `total_rows` over `tables` tables; the sum is exactly `total_rows`."""
    if not 1 <= tables <= MAX_TABLES:
        raise ValueError(f"tables must be 1..{MAX_TABLES}")
    if total_rows < tables * MIN_ROWS:
        raise ValueError(f"rows must be at least {MIN_ROWS} per table")
    if large_every < 1 or large_factor < 1:
        raise ValueError("large_every and large_factor must be positive")
    weights = [large_factor if i % large_every == 0 else 1 for i in range(1, tables + 1)]
    total_weight = sum(weights)
    rows = [max(MIN_ROWS, total_rows * w // total_weight) for w in weights]
    # Rounding: the remainder goes to (or is taken from) the largest table.
    largest = max(range(tables), key=lambda i: rows[i])
    rows[largest] += total_rows - sum(rows)
    if rows[largest] < MIN_ROWS:
        raise ValueError("cannot split the rows")
    return [Table(i + 1, rows[i], KINDS[i % len(KINDS)]) for i in range(tables)]


# ------------------------------------------------------------------------------------ values
def fr_iban(bban: str) -> str:
    """French IBAN of a 23-digit BBAN (ISO 7064 mod 97-10 check digits, F = 15, R = 27)."""
    if len(bban) != 23 or not bban.isdigit():
        raise ValueError("a French BBAN has 23 digits here")
    check = 98 - int(bban + "152700") % 97
    return f"FR{check:02d}{bban}"


def bban(table: int, row: int) -> str:
    return f"{BANK_CODE}{table:05d}{row:011d}{row % 97:02d}"


def email(table: int, row: int) -> str:
    first = FIRST_NAMES[row % len(FIRST_NAMES)]
    last = LAST_NAMES[(row // len(FIRST_NAMES)) % len(LAST_NAMES)]
    n = row // (len(FIRST_NAMES) * len(LAST_NAMES))
    return f"{first}.{last}{n}@{MAIL_DOMAINS[(row + table) % len(MAIL_DOMAINS)]}"


def phone(table: int, row: int) -> str:
    return f"+33 6 {row % 100:02d} {row // 100 % 100:02d} {row // 10000 % 100:02d} {table % 100:02d}"


def row_values(table: Table, row: int) -> dict[str, object]:
    """Reference values of one row (the SQL and JavaScript generators compute the same)."""
    v: dict[str, object] = {
        "id": row,
        "status": STATUSES[row % len(STATUSES)],
        "note": f"order {row} batch {row % 97}",
    }
    for c in table.columns:
        if c == "email":
            v[c] = email(table.index, row)
        elif c == "phone":
            v[c] = phone(table.index, row)
        elif c == "iban":
            v[c] = fr_iban(bban(table.index, row))
        elif c == "amount":
            v[c] = f"{row % 100000 / 100:.2f}"
        elif c == "quantity":
            v[c] = row % 50 + 1
    return v


def _sql_list(values: tuple[str, ...]) -> str:
    return ", ".join(f"'{v}'" for v in values)


# ------------------------------------------------------------------------------------ PostgreSQL
def pg_sql(tables: list[Table]) -> str:
    """Schemas, tables, rows, statistics and grants (agent: SELECT; load_app: SELECT)."""
    names = f"ARRAY[{_sql_list(FIRST_NAMES)}]"
    lasts = f"ARRAY[{_sql_list(LAST_NAMES)}]"
    doms = f"ARRAY[{_sql_list(MAIL_DOMAINS)}]"
    stats = f"ARRAY[{_sql_list(STATUSES)}]"
    nf, nl, nd = len(FIRST_NAMES), len(LAST_NAMES), len(MAIL_DOMAINS)
    out = [
        "\\set ON_ERROR_STOP on",
        "SET client_min_messages = warning;",
        # The data is synthetic: keep it out of pg_stat_statements' texts and the statement log.
        "SET pg_stat_statements.track = none;",
    ]
    for s in PG_SCHEMAS:
        out.append(f"CREATE SCHEMA IF NOT EXISTS {s};")
    for t in tables:
        types = {"email": "text", "phone": "text", "iban": "text", "amount": "numeric(12,2)",
                 "quantity": "integer"}
        exprs = {
            "email": (f"({names})[1 + s.g % {nf}] || '.' || ({lasts})[1 + (s.g / {nf}) % {nl}]"
                      f" || (s.g / {nf * nl})::text || '@' || ({doms})[1 + (s.g + {t.index}) % {nd}]"),
            "phone": (f"'+33 6 ' || lpad((s.g % 100)::text, 2, '0') || ' ' || lpad((s.g / 100 % 100)::text, 2, '0')"
                      f" || ' ' || lpad((s.g / 10000 % 100)::text, 2, '0') || ' {t.index % 100:02d}'"),
            "iban": "'FR' || lpad((98 - mod((s.bban || '152700')::numeric, 97))::text, 2, '0') || s.bban",
            "amount": "((s.g % 100000) / 100.0)::numeric(12,2)",
            "quantity": "(s.g % 50 + 1)::integer",
        }
        cols = ", ".join(f"{c} {types[c]}" for c in t.columns)
        out.append(
            f"CREATE TABLE {t.pg_name} (id bigint PRIMARY KEY, created_at timestamptz NOT NULL, "
            f"status text NOT NULL, note text, {cols});"
        )
        sel = ", ".join(exprs[c] for c in t.columns)
        out.append(
            f"INSERT INTO {t.pg_name} SELECT s.g, timestamptz '2024-01-01 00:00:00+00' + s.g * interval '1 minute', "
            f"({stats})[1 + s.g % {len(STATUSES)}], 'order ' || s.g || ' batch ' || (s.g % 97), {sel} "
            f"FROM (SELECT g, '{BANK_CODE}' || lpad('{t.index}', 5, '0') || lpad(g::text, 11, '0') "
            f"|| lpad((g % 97)::text, 2, '0') AS bban FROM generate_series(1, {t.rows}) AS g) AS s;"
        )
    schemas = ", ".join(PG_SCHEMAS)
    out += [
        # Visibility map and statistics now, so that autovacuum does not run during the measurement
        # windows, and reltuples drives the agent's TABLESAMPLE choice as on a live database.
        f"VACUUM (ANALYZE) {', '.join(t.pg_name for t in tables)};",
        # Flush the load now rather than at a timed checkpoint inside a measurement window.
        "CHECKPOINT;",
        f"GRANT USAGE ON SCHEMA {schemas} TO databastion_agent, load_app;",
        f"GRANT SELECT ON ALL TABLES IN SCHEMA {schemas} TO databastion_agent, load_app;",
        "SELECT count(*) || ' tables' FROM pg_tables WHERE schemaname IN ("
        + _sql_list(PG_SCHEMAS) + ");",
    ]
    return "\n".join(out) + "\n"


# ------------------------------------------------------------------------------------ MariaDB
def mariadb_sql(tables: list[Table]) -> str:
    nf, nl, nd = len(FIRST_NAMES), len(LAST_NAMES), len(MAIL_DOMAINS)
    types = {"email": "VARCHAR(128)", "phone": "VARCHAR(32)", "iban": "VARCHAR(34)",
             "amount": "DECIMAL(12,2)", "quantity": "INT"}
    out = [f"USE {MARIADB_DATABASE};"]
    for t in tables:
        exprs = {
            "email": (f"CONCAT(ELT(1 + s.g % {nf}, {_sql_list(FIRST_NAMES)}), '.', "
                      f"ELT(1 + (s.g DIV {nf}) % {nl}, {_sql_list(LAST_NAMES)}), s.g DIV {nf * nl}, '@', "
                      f"ELT(1 + (s.g + {t.index}) % {nd}, {_sql_list(MAIL_DOMAINS)}))"),
            "phone": (f"CONCAT('+33 6 ', LPAD(s.g % 100, 2, '0'), ' ', LPAD(s.g DIV 100 % 100, 2, '0'), ' ', "
                      f"LPAD(s.g DIV 10000 % 100, 2, '0'), ' {t.index % 100:02d}')"),
            "iban": ("CONCAT('FR', LPAD(98 - MOD(CAST(CONCAT(s.bban, '152700') AS DECIMAL(65,0)), 97), 2, '0'), "
                     "s.bban)"),
            "amount": "CAST((s.g % 100000) / 100 AS DECIMAL(12,2))",
            "quantity": "s.g % 50 + 1",
        }
        cols = ", ".join(f"{c} {types[c]}" for c in t.columns)
        out.append(
            f"CREATE TABLE {t.mariadb_name} (id BIGINT NOT NULL PRIMARY KEY, created_at DATETIME NOT NULL, "
            f"status VARCHAR(16) NOT NULL, note VARCHAR(80), {cols}) ENGINE=InnoDB;"
        )
        sel = ", ".join(exprs[c] for c in t.columns)
        out.append(
            f"INSERT INTO {t.mariadb_name} SELECT s.g, TIMESTAMP '2024-01-01 00:00:00' + INTERVAL s.g MINUTE, "
            f"ELT(1 + s.g % {len(STATUSES)}, {_sql_list(STATUSES)}), CONCAT('order ', s.g, ' batch ', s.g % 97), {sel} "
            f"FROM (SELECT seq AS g, CONCAT('{BANK_CODE}', LPAD({t.index}, 5, '0'), LPAD(seq, 11, '0'), "
            f"LPAD(seq % 97, 2, '0')) AS bban FROM seq_1_to_{t.rows}) AS s;"
        )
    out.append(f"ANALYZE TABLE {', '.join(t.mariadb_name for t in tables)};")
    out.append(
        f"SELECT CONCAT(COUNT(*), ' tables') FROM information_schema.TABLES "
        f"WHERE TABLE_SCHEMA = '{MARIADB_DATABASE}' AND TABLE_NAME LIKE 'load\\_t%';"
    )
    return "\n".join(out) + "\n"


# ------------------------------------------------------------------------------------ MongoDB
def mongo_js(tables: list[Table], batch: int = 5000) -> str:
    """JavaScript for mongosh, run after a prefix that defines `c` (a root connection)."""
    spec = ", ".join(f'["{t.mongo_name}", {t.index}, {t.rows}, "{t.kind}"]' for t in tables)
    return f"""
const app = c.getSiblingDB("{MONGO_DATABASE}");
const FIRST = [{_sql_list(FIRST_NAMES).replace("'", '"')}];
const LAST = [{_sql_list(LAST_NAMES).replace("'", '"')}];
const DOMS = [{_sql_list(MAIL_DOMAINS).replace("'", '"')}];
const STATUS = [{_sql_list(STATUSES).replace("'", '"')}];
const pad = (n, w) => String(n).padStart(w, "0");
const bban = (t, g) => "{BANK_CODE}" + pad(t, 5) + pad(g, 11) + pad(g % 97, 2);
const iban = (b) => "FR" + pad(Number(98n - BigInt(b + "152700") % 97n), 2) + b;
const email = (t, g) => FIRST[g % {len(FIRST_NAMES)}] + "." + LAST[Math.floor(g / {len(FIRST_NAMES)}) % {len(LAST_NAMES)}]
  + Math.floor(g / {len(FIRST_NAMES) * len(LAST_NAMES)}) + "@" + DOMS[(g + t) % {len(MAIL_DOMAINS)}];
const phone = (t, g) => "+33 6 " + pad(g % 100, 2) + " " + pad(Math.floor(g / 100) % 100, 2) + " "
  + pad(Math.floor(g / 10000) % 100, 2) + " " + pad(t % 100, 2);
const COLS = {{contact: ["email", "phone"], billing: ["iban", "amount"], plain: ["amount", "quantity"],
  mixed: ["email", "phone", "iban"]}};
let total = 0;
for (const [name, t, rows, kind] of [{spec}]) {{
  const coll = app.getCollection(name);
  for (let start = 1; start <= rows; start += {batch}) {{
    const docs = [];
    for (let g = start; g < Math.min(start + {batch}, rows + 1); g++) {{
      const d = {{_id: g, created_at: new Date(Date.UTC(2024, 0, 1) + g * 60000), status: STATUS[g % {len(STATUSES)}],
        note: "order " + g + " batch " + (g % 97)}};
      for (const col of COLS[kind]) {{
        if (col === "email") d.email = email(t, g);
        else if (col === "phone") d.phone = phone(t, g);
        else if (col === "iban") d.iban = iban(bban(t, g));
        else if (col === "amount") d.amount = (g % 100000) / 100;
        else if (col === "quantity") d.quantity = g % 50 + 1;
      }}
      docs.push(d);
    }}
    coll.insertMany(docs, {{ordered: false}});
  }}
  total += coll.estimatedDocumentCount();
}}
print(total + " documents");
"""


# ------------------------------------------------------------------------------------ workloads
def workload_tables(tables: list[Table], n: int) -> list[Table]:
    if not 1 <= n <= MAX_WORKLOAD_TABLES:
        raise ValueError(f"workload tables must be 1..{MAX_WORKLOAD_TABLES}")
    return tables[:n]


def pgbench_scripts(tables: list[Table]) -> dict[str, str]:
    """One point-select script per table; pgbench picks one at random per transaction (-f x@1)."""
    return {
        f"pg_t{t.tag}.sql": f"\\set id random(1, {t.rows})\nSELECT * FROM {t.pg_name} WHERE id = :id;\n"
        for t in tables
    }


def sysbench_lua(tables: list[Table]) -> str:
    rows = "\n".join(f'  {{"{t.mariadb_name}", {t.rows}}},' for t in tables)
    return f"""-- Generated by e2e/load/seed.py: point selects on the load tables of `{MARIADB_DATABASE}`.
local tables = {{
{rows}
}}

function thread_init()
  drv = sysbench.sql.driver()
  con = drv:connect()
end

function thread_done()
  con:disconnect()
end

function event()
  local t = tables[sysbench.rand.uniform(1, #tables)]
  con:query(string.format("SELECT * FROM %s WHERE id = %d", t[1], sysbench.rand.uniform(1, t[2])))
end
"""


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("what", choices=["plan", "pg", "mariadb", "mongo", "pgbench", "sysbench"])
    p.add_argument("--tables", type=int, required=True)
    p.add_argument("--rows", type=int, required=True)
    p.add_argument("--out", help="output directory (pgbench)")
    p.add_argument("--workload-tables", type=int, default=40,
                   help="tables the pgbench / sysbench workload reads (the first ones of the plan)")
    a = p.parse_args(argv)
    try:
        tables = plan(a.tables, a.rows)
        hot = workload_tables(tables, min(a.workload_tables, len(tables)))
    except ValueError as e:
        print(f"seed.py: {e}", file=sys.stderr)
        return 2
    if a.what == "plan":
        for t in tables:
            print(t.index, t.pg_name, t.rows, t.kind)
    elif a.what == "pg":
        sys.stdout.write(pg_sql(tables))
    elif a.what == "mariadb":
        sys.stdout.write(mariadb_sql(tables))
    elif a.what == "mongo":
        sys.stdout.write(mongo_js(tables))
    elif a.what == "sysbench":
        sys.stdout.write(sysbench_lua(hot))
    else:
        if not a.out:
            print("seed.py: --out is required for pgbench", file=sys.stderr)
            return 2
        os.makedirs(a.out, exist_ok=True)
        for name, text in pgbench_scripts(hot).items():
            with open(os.path.join(a.out, name), "w", encoding="utf-8") as f:
                f.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
