//! Generator of the `databastion-protocol` types (task P0-B, invariant I6).
//!
//! Reads `shared/protocol/openapi.yaml`, extracts `components/schemas`,
//! rewrites `#/components/schemas/X` references to `#/$defs/X` (the same
//! transformation the console's Ajv validation applies), and turns the
//! resulting JSON Schema 2020-12 document into Rust types with
//! [`typify`](https://github.com/oxidecomputer/typify).
//!
//! The output is committed as `crates/protocol/src/generated.rs`; the
//! `drift` test of `databastion-protocol` regenerates it in memory and fails
//! if the committed file is stale. Regenerate with (from `agent/`):
//!
//! ```sh
//! cargo run -p databastion-protocol-codegen
//! ```
//!
//! This crate is a developer tool: it is never a dependency of the agent
//! binary, and it performs no network access.

#![forbid(unsafe_code)]

use std::path::{Path, PathBuf};

use serde_json::{Map, Value};

/// Header written at the top of the generated file.
const HEADER: &str = "\
// @generated by databastion-protocol-codegen from shared/protocol/openapi.yaml.
// DO NOT EDIT: run `cargo run -p databastion-protocol-codegen` from `agent/`.
";

/// Prefix of OpenAPI component references.
const OPENAPI_REF_PREFIX: &str = "#/components/schemas/";
/// Prefix of JSON Schema definition references.
const DEFS_REF_PREFIX: &str = "#/$defs/";

/// Code generation errors.
#[derive(Debug, thiserror::Error)]
pub enum CodegenError {
    /// The OpenAPI file could not be read or written.
    #[error("I/O error on {path}: {source}")]
    Io {
        /// File concerned.
        path: PathBuf,
        /// Underlying error.
        source: std::io::Error,
    },
    /// The OpenAPI document is not valid YAML.
    #[error("invalid YAML: {0}")]
    Yaml(#[from] serde_yaml::Error),
    /// The schemas could not be converted into a JSON Schema document.
    #[error("invalid JSON Schema: {0}")]
    Json(#[from] serde_json::Error),
    /// `components/schemas` is missing or not a mapping.
    #[error("openapi.yaml has no components/schemas mapping")]
    NoSchemas,
    /// typify rejected a schema.
    #[error("typify: {0}")]
    Typify(#[from] typify::Error),
    /// typify produced code that does not parse.
    #[error("generated code does not parse: {0}")]
    Syn(#[from] syn::Error),
}

/// Path of `shared/protocol/openapi.yaml`, relative to the workspace.
#[must_use]
pub fn default_openapi_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../shared/protocol/openapi.yaml")
}

/// Path of the committed generated file.
#[must_use]
pub fn default_output_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../protocol/src/generated.rs")
}

/// Extracts `components/schemas` from an OpenAPI 3.1 document as a JSON
/// Schema 2020-12 document whose `$defs` are the component schemas.
///
/// # Errors
/// If the YAML is invalid or has no `components/schemas` mapping.
pub fn json_schema_from_openapi(openapi_yaml: &str) -> Result<Value, CodegenError> {
    let doc: Value = serde_yaml::from_str(openapi_yaml)?;
    let mut schemas = doc
        .get("components")
        .and_then(|c| c.get("schemas"))
        .cloned()
        .ok_or(CodegenError::NoSchemas)?;
    if !schemas.is_object() {
        return Err(CodegenError::NoSchemas);
    }
    rewrite_refs(&mut schemas);
    Ok(wrap(schemas))
}

fn wrap(schemas: Value) -> Value {
    let mut root = Map::new();
    root.insert(
        "$schema".to_owned(),
        Value::String("https://json-schema.org/draft/2020-12/schema".to_owned()),
    );
    root.insert("$defs".to_owned(), schemas);
    Value::Object(root)
}

/// Keywords typify cannot express (it panics on them). They are removed
/// before generation and listed in the generated file header. Their rules
/// are enforced by the console's Ajv validation and by the agent's own
/// sanitizer before spooling, not by serde.
const UNSUPPORTED_KEYWORDS: [&str; 3] = ["if", "then", "else"];

/// Anchors unanchored `pattern`s: `P` becomes `^[\s\S]*?(?:P)`.
///
/// JSON Schema patterns are unanchored searches. typify merges the patterns
/// of an `allOf` into lookaheads (`(?=A)(?=B)`) evaluated at the first
/// position where `A` matches, so an unanchored `B` (e.g. `MaskedSample`'s
/// "contains a `*`" rule) would only be tested at that position. The
/// rewritten pattern matches exactly the same strings on its own, and stays
/// correct once merged.
fn anchor_patterns(value: &mut Value, pointer: &str, rewritten: &mut Vec<String>) {
    match value {
        Value::Object(map) => {
            for (key, child) in map.iter_mut() {
                let child_pointer = format!("{pointer}/{key}");
                match child {
                    Value::String(pattern) if key == "pattern" && !pattern.starts_with('^') => {
                        *pattern = format!("^[\\s\\S]*?(?:{pattern})");
                        rewritten.push(child_pointer);
                    }
                    _ => anchor_patterns(child, &child_pointer, rewritten),
                }
            }
        }
        Value::Array(items) => {
            for (i, child) in items.iter_mut().enumerate() {
                anchor_patterns(child, &format!("{pointer}/{i}"), rewritten);
            }
        }
        _ => {}
    }
}

/// Rewrites `const: X` as `enum: [X]` (same meaning in JSON Schema).
///
/// typify ignores `const` on a string property (it generates a free
/// `String`), so the `type` discriminator of each `Job` variant would accept
/// any value, e.g. `shell.exec`. A one-value `enum` becomes a one-variant
/// Rust enum, which serde enforces.
fn const_to_enum(value: &mut Value, pointer: &str, rewritten: &mut Vec<String>) {
    match value {
        Value::Object(map) => {
            if !map.contains_key("enum") {
                if let Some(constant) = map.remove("const") {
                    map.insert("enum".to_owned(), Value::Array(vec![constant]));
                    rewritten.push(format!("{pointer}/const"));
                }
            }
            for (key, child) in map.iter_mut() {
                const_to_enum(child, &format!("{pointer}/{key}"), rewritten);
            }
        }
        Value::Array(items) => {
            for (i, child) in items.iter_mut().enumerate() {
                const_to_enum(child, &format!("{pointer}/{i}"), rewritten);
            }
        }
        _ => {}
    }
}

/// Collects the JSON pointers of `not` keywords: typify ignores them on
/// string schemas, so they are reported in the generated file header.
fn collect_not(value: &Value, pointer: &str, found: &mut Vec<String>) {
    match value {
        Value::Object(map) => {
            for (key, child) in map {
                let child_pointer = format!("{pointer}/{key}");
                if key == "not" {
                    found.push(child_pointer.clone());
                }
                collect_not(child, &child_pointer, found);
            }
        }
        Value::Array(items) => {
            for (i, child) in items.iter().enumerate() {
                collect_not(child, &format!("{pointer}/{i}"), found);
            }
        }
        _ => {}
    }
}

/// Compiles every schema pattern with the ECMAScript `u` flag.
///
/// typify emits `regress::Regex::new(pattern)`, i.e. without flags, where
/// `\p{L}` is not a Unicode property escape. The contract's patterns need
/// the `u` flag, as in Ajv (see `shared/protocol/README.md`); this rewrites
/// each call to `regress::Regex::with_flags(pattern, "u")`.
struct UnicodePatterns {
    rewritten: usize,
}

impl syn::visit_mut::VisitMut for UnicodePatterns {
    fn visit_expr_call_mut(&mut self, call: &mut syn::ExprCall) {
        syn::visit_mut::visit_expr_call_mut(self, call);
        let syn::Expr::Path(func) = &mut *call.func else {
            return;
        };
        let segments: Vec<String> = func
            .path
            .segments
            .iter()
            .map(|s| s.ident.to_string())
            .collect();
        if segments == ["regress", "Regex", "new"] && call.args.len() == 1 {
            func.path = syn::parse_quote!(::regress::Regex::with_flags);
            call.args.push(syn::parse_quote!("u"));
            self.rewritten += 1;
        }
    }
}

/// Removes `Default` from the derives of every struct that has fields: a
/// defaulted protocol value is never meaningful, and data must be built
/// explicitly (field-less structs such as `EmptyParams` keep it).
fn strip_default_derives(file: &mut syn::File) {
    for item in &mut file.items {
        let syn::Item::Struct(item) = item else {
            continue;
        };
        if item.fields.is_empty() {
            continue;
        }
        for attr in &mut item.attrs {
            if !attr.path().is_ident("derive") {
                continue;
            }
            let Ok(paths) = attr.parse_args_with(
                syn::punctuated::Punctuated::<syn::Path, syn::Token![,]>::parse_terminated,
            ) else {
                continue;
            };
            let kept = paths
                .into_iter()
                .filter(|p| p.segments.last().is_none_or(|s| s.ident != "Default"));
            *attr = syn::parse_quote!(#[derive(#(#kept),*)]);
        }
    }
}

/// Removes [`UNSUPPORTED_KEYWORDS`] from every schema object and returns the
/// JSON pointers (under `$defs`) of the removed keywords, sorted.
fn strip_unsupported(value: &mut Value, pointer: &str, removed: &mut Vec<String>) {
    match value {
        Value::Object(map) => {
            for keyword in UNSUPPORTED_KEYWORDS {
                if map.remove(keyword).is_some() {
                    removed.push(format!("{pointer}/{keyword}"));
                }
            }
            for (key, child) in map.iter_mut() {
                strip_unsupported(child, &format!("{pointer}/{key}"), removed);
            }
        }
        Value::Array(items) => {
            for (i, child) in items.iter_mut().enumerate() {
                strip_unsupported(child, &format!("{pointer}/{i}"), removed);
            }
        }
        _ => {}
    }
}

/// Rewrites every `$ref: "#/components/schemas/X"` to `#/$defs/X`.
fn rewrite_refs(value: &mut Value) {
    match value {
        Value::Object(map) => {
            for (key, child) in map.iter_mut() {
                if key == "$ref" {
                    if let Value::String(target) = child {
                        if let Some(name) = target.strip_prefix(OPENAPI_REF_PREFIX) {
                            *target = format!("{DEFS_REF_PREFIX}{name}");
                        }
                    }
                } else {
                    rewrite_refs(child);
                }
            }
        }
        Value::Array(items) => items.iter_mut().for_each(rewrite_refs),
        _ => {}
    }
}

/// Generates the Rust source of `databastion-protocol`'s `generated` module.
///
/// # Errors
/// If the document cannot be parsed or typify rejects a schema.
pub fn generate(openapi_yaml: &str) -> Result<String, CodegenError> {
    let mut schema = json_schema_from_openapi(openapi_yaml)?;
    let mut removed = Vec::new();
    if let Some(defs) = schema.get_mut("$defs") {
        strip_unsupported(defs, "#/$defs", &mut removed);
    }
    removed.sort();
    let mut anchored = Vec::new();
    if let Some(defs) = schema.get_mut("$defs") {
        anchor_patterns(defs, "#/$defs", &mut anchored);
    }
    anchored.sort();
    let mut constants = Vec::new();
    if let Some(defs) = schema.get_mut("$defs") {
        const_to_enum(defs, "#/$defs", &mut constants);
    }
    constants.sort();
    let mut negations = Vec::new();
    if let Some(defs) = schema.get("$defs") {
        collect_not(defs, "#/$defs", &mut negations);
    }
    negations.sort();
    let root: schemars::schema::RootSchema = serde_json::from_value(schema)?;
    let mut settings = typify::TypeSpaceSettings::default();
    settings.with_struct_builder(false);
    let mut space = typify::TypeSpace::new(&settings);
    space.add_root_schema(root)?;
    let mut file: syn::File = syn::parse2(space.to_stream())?;
    strip_default_derives(&mut file);
    let mut unicode = UnicodePatterns { rewritten: 0 };
    syn::visit_mut::VisitMut::visit_file_mut(&mut unicode, &mut file);
    let mut out = String::from(HEADER);
    out.push_str(
        "//\n// Keywords not expressible by typify, removed before generation and enforced\n\
         // by the console's Ajv validation and the agent's sanitizer instead:\n",
    );
    for pointer in &removed {
        out.push_str("// - ");
        out.push_str(pointer);
        out.push('\n');
    }
    out.push_str(
        "//\n// `not` keywords (not enforced by the generated types; same enforcement points):\n",
    );
    for pointer in &negations {
        out.push_str("// - ");
        out.push_str(pointer);
        out.push('\n');
    }
    out.push_str(&format!(
        "//\n// Patterns compiled with the ECMAScript `u` flag, as in Ajv: {}.\n",
        unicode.rewritten
    ));
    out.push_str("//\n// `const: X` rewritten as `enum: [X]` (typify ignores string `const`):\n");
    for pointer in &constants {
        out.push_str("// - ");
        out.push_str(pointer);
        out.push('\n');
    }
    out.push_str("//\n// Unanchored patterns rewritten as `^[\\s\\S]*?(?:P)` (same language):\n");
    for pointer in &anchored {
        out.push_str("// - ");
        out.push_str(pointer);
        out.push('\n');
    }
    out.push('\n');
    out.push_str(&prettyplease::unparse(&file));
    Ok(out)
}

/// Reads `openapi_path` and returns the generated source.
///
/// # Errors
/// On I/O or generation errors.
pub fn generate_from_file(openapi_path: &Path) -> Result<String, CodegenError> {
    let yaml = std::fs::read_to_string(openapi_path).map_err(|source| CodegenError::Io {
        path: openapi_path.to_owned(),
        source,
    })?;
    generate(&yaml)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn refs_are_rewritten_to_defs() {
        let yaml = r##"
components:
  schemas:
    A:
      type: object
      properties:
        b: { $ref: "#/components/schemas/B" }
    B: { type: string, maxLength: 3 }
"##;
        let schema = json_schema_from_openapi(yaml).unwrap();
        assert_eq!(
            schema["$defs"]["A"]["properties"]["b"]["$ref"],
            Value::String("#/$defs/B".to_owned())
        );
    }

    #[test]
    fn missing_schemas_is_an_error() {
        assert!(matches!(
            json_schema_from_openapi("openapi: 3.1.0\n"),
            Err(CodegenError::NoSchemas)
        ));
    }

    #[test]
    fn conditionals_are_stripped_and_reported() {
        let mut value = serde_json::json!({
            "A": { "type": "object", "if": {}, "then": {}, "properties": { "x": { "else": {} } } }
        });
        let mut removed = Vec::new();
        strip_unsupported(&mut value, "#/$defs", &mut removed);
        removed.sort();
        assert_eq!(
            removed,
            [
                "#/$defs/A/if",
                "#/$defs/A/properties/x/else",
                "#/$defs/A/then"
            ]
        );
        assert!(value["A"].get("if").is_none());
    }

    #[test]
    fn unanchored_patterns_are_anchored() {
        let mut value = serde_json::json!({
            "A": { "pattern": "\\*", "allOf": [{ "pattern": "^x$" }] }
        });
        let mut rewritten = Vec::new();
        anchor_patterns(&mut value, "#/$defs", &mut rewritten);
        assert_eq!(value["A"]["pattern"], "^[\\s\\S]*?(?:\\*)");
        assert_eq!(value["A"]["allOf"][0]["pattern"], "^x$");
        assert_eq!(rewritten, ["#/$defs/A/pattern"]);
    }

    #[test]
    fn patterns_get_the_unicode_flag() {
        let mut file: syn::File = syn::parse_quote! {
            fn f() { let _ = ::regress::Regex::new("^\\p{L}$").unwrap(); }
        };
        let mut unicode = UnicodePatterns { rewritten: 0 };
        syn::visit_mut::VisitMut::visit_file_mut(&mut unicode, &mut file);
        assert_eq!(unicode.rewritten, 1);
        let text = quote::quote!(#file).to_string();
        assert!(
            text.contains("with_flags (\"^\\\\p{L}$\" , \"u\")"),
            "{text}"
        );
    }

    #[test]
    fn const_becomes_one_value_enum() {
        let mut value = serde_json::json!({
            "A": { "properties": { "type": { "type": "string", "const": "x.y" } } }
        });
        let mut rewritten = Vec::new();
        const_to_enum(&mut value, "#/$defs", &mut rewritten);
        assert_eq!(
            value["A"]["properties"]["type"]["enum"],
            serde_json::json!(["x.y"])
        );
        assert!(value["A"]["properties"]["type"].get("const").is_none());
        assert_eq!(rewritten, ["#/$defs/A/properties/type/const"]);
    }

    #[test]
    fn default_is_stripped_from_data_structs_only() {
        let mut file: syn::File = syn::parse_quote! {
            #[derive(Clone, Default)]
            pub struct Data { pub a: u8 }
            #[derive(Clone, Default)]
            pub struct Empty {}
        };
        strip_default_derives(&mut file);
        let text = quote::quote!(#file).to_string();
        assert!(text.contains("derive (Clone)] pub struct Data"), "{text}");
        assert!(
            text.contains("derive (Clone , Default)] pub struct Empty"),
            "{text}"
        );
    }
}
