//! Generator of the `databastion-protocol` types (task P0-B, invariant I6).
//!
//! Reads `shared/protocol/openapi.yaml`, extracts `components/schemas`,
//! rewrites `#/components/schemas/X` references to `#/$defs/X` (the same
//! transformation the console's Ajv validation applies), and turns the
//! resulting JSON Schema 2020-12 document into Rust types with
//! [`typify`](https://github.com/oxidecomputer/typify).
//!
//! The output is committed as `crates/protocol/src/generated.rs`; the
//! `drift` test of `databastion-protocol` regenerates it in memory and fails
//! if the committed file is stale. Regenerate with (from `agent/`):
//!
//! ```sh
//! cargo run -p databastion-protocol-codegen
//! ```
//!
//! This crate is a developer tool: it is never a dependency of the agent
//! binary, and it performs no network access.

#![forbid(unsafe_code)]

use std::path::{Path, PathBuf};

use serde_json::{Map, Value};

/// Header written at the top of the generated file.
const HEADER: &str = "\
// @generated by databastion-protocol-codegen from shared/protocol/openapi.yaml.
// DO NOT EDIT: run `cargo run -p databastion-protocol-codegen` from `agent/`.
";

/// Prefix of OpenAPI component references.
const OPENAPI_REF_PREFIX: &str = "#/components/schemas/";
/// Prefix of JSON Schema definition references.
const DEFS_REF_PREFIX: &str = "#/$defs/";

/// Code generation errors.
#[derive(Debug, thiserror::Error)]
pub enum CodegenError {
    /// The OpenAPI file could not be read or written.
    #[error("I/O error on {path}: {source}")]
    Io {
        /// File concerned.
        path: PathBuf,
        /// Underlying error.
        source: std::io::Error,
    },
    /// The OpenAPI document is not valid YAML.
    #[error("invalid YAML: {0}")]
    Yaml(#[from] serde_yaml_ng::Error),
    /// The schemas could not be converted into a JSON Schema document.
    #[error("invalid JSON Schema: {0}")]
    Json(#[from] serde_json::Error),
    /// `components/schemas` is missing or not a mapping.
    #[error("openapi.yaml has no components/schemas mapping")]
    NoSchemas,
    /// typify rejected a schema.
    #[error("typify: {0}")]
    Typify(#[from] typify::Error),
    /// typify produced code that does not parse.
    #[error("generated code does not parse: {0}")]
    Syn(#[from] syn::Error),
}

/// Path of `shared/protocol/openapi.yaml`, relative to the workspace.
#[must_use]
pub fn default_openapi_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../shared/protocol/openapi.yaml")
}

/// Path of the committed generated file.
#[must_use]
pub fn default_output_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../protocol/src/generated.rs")
}

/// Extracts `components/schemas` from an OpenAPI 3.1 document as a JSON
/// Schema 2020-12 document whose `$defs` are the component schemas.
///
/// # Errors
/// If the YAML is invalid or has no `components/schemas` mapping.
pub fn json_schema_from_openapi(openapi_yaml: &str) -> Result<Value, CodegenError> {
    let doc: Value = serde_yaml_ng::from_str(openapi_yaml)?;
    let mut schemas = doc
        .get("components")
        .and_then(|c| c.get("schemas"))
        .cloned()
        .ok_or(CodegenError::NoSchemas)?;
    if !schemas.is_object() {
        return Err(CodegenError::NoSchemas);
    }
    walk_defs(&mut schemas, "#/$defs", &mut rewrite_ref);
    Ok(wrap(schemas))
}

fn wrap(schemas: Value) -> Value {
    let mut root = Map::new();
    root.insert(
        "$schema".to_owned(),
        Value::String("https://json-schema.org/draft/2020-12/schema".to_owned()),
    );
    root.insert("$defs".to_owned(), schemas);
    Value::Object(root)
}

/// Schemas replaced by hand-written types of `databastion-protocol`:
/// credentials (redacted `Debug`, zeroized, `src/secret.rs`) and UUIDs
/// (canonical lowercase, version 7 checked, `src/ids.rs`).
pub const REPLACEMENTS: [(&str, &str); 4] = [
    ("AgentSecret", "crate::secret::AgentSecret"),
    ("EnrollmentToken", "crate::secret::EnrollmentToken"),
    ("Uuid", "crate::ids::Uuid"),
    ("UuidV7", "crate::ids::UuidV7"),
];

/// Keywords typify cannot express (it panics on them). They are removed
/// before generation and listed in the generated file header. Their rules
/// are enforced by the console's Ajv validation, not by serde; agent-side
/// checks of received values are a required future step (P1-B, P2).
const UNSUPPORTED_KEYWORDS: [&str; 3] = ["if", "then", "else"];

/// Compiles every schema pattern with the ECMAScript `u` flag.
///
/// typify emits `regress::Regex::new(pattern)`, i.e. without flags, where
/// `\p{L}` is not a Unicode property escape. The contract's patterns need
/// the `u` flag, as in Ajv (see `shared/protocol/README.md`); this rewrites
/// each call to `regress::Regex::with_flags(pattern, "u")`.
struct UnicodePatterns {
    rewritten: usize,
}

impl syn::visit_mut::VisitMut for UnicodePatterns {
    fn visit_expr_call_mut(&mut self, call: &mut syn::ExprCall) {
        syn::visit_mut::visit_expr_call_mut(self, call);
        let syn::Expr::Path(func) = &mut *call.func else {
            return;
        };
        let segments: Vec<String> = func
            .path
            .segments
            .iter()
            .map(|s| s.ident.to_string())
            .collect();
        if segments == ["regress", "Regex", "new"] && call.args.len() == 1 {
            func.path = syn::parse_quote!(::regress::Regex::with_flags);
            call.args.push(syn::parse_quote!("u"));
            self.rewritten += 1;
        }
    }
}

/// Removes `Default` from the derives of every struct that has fields: a
/// defaulted protocol value is never meaningful, and data must be built
/// explicitly (field-less structs such as `EmptyParams` keep it).
fn strip_default_derives(file: &mut syn::File) {
    for item in &mut file.items {
        let syn::Item::Struct(item) = item else {
            continue;
        };
        if item.fields.is_empty() {
            continue;
        }
        for attr in &mut item.attrs {
            if !attr.path().is_ident("derive") {
                continue;
            }
            let Ok(paths) = attr.parse_args_with(
                syn::punctuated::Punctuated::<syn::Path, syn::Token![,]>::parse_terminated,
            ) else {
                continue;
            };
            let kept = paths
                .into_iter()
                .filter(|p| p.segments.last().is_none_or(|s| s.ident != "Default"));
            *attr = syn::parse_quote!(#[derive(#(#kept),*)]);
        }
    }
}

/// Keywords whose value is a map of subschemas (property names as keys).
const SCHEMA_MAP_KEYWORDS: [&str; 5] = [
    "properties",
    "patternProperties",
    "$defs",
    "definitions",
    "dependentSchemas",
];
/// Keywords whose value is a single subschema.
const SCHEMA_KEYWORDS: [&str; 11] = [
    "items",
    "additionalItems",
    "additionalProperties",
    "unevaluatedItems",
    "unevaluatedProperties",
    "propertyNames",
    "contains",
    "not",
    "if",
    "then",
    "else",
];
/// Keywords whose value is an array of subschemas.
const SCHEMA_ARRAY_KEYWORDS: [&str; 4] = ["allOf", "anyOf", "oneOf", "prefixItems"];

/// Calls `visit` on every schema object reachable from `schema`, following
/// only subschema keywords. Property names under `properties`, and the
/// values of `enum`, `const`, `default`, `examples` or `description`, are
/// never visited, so a property called `pattern` or an example containing
/// `const` is not rewritten. `visit` runs before the children are walked.
fn walk_schema(
    schema: &mut Value,
    pointer: &str,
    visit: &mut dyn FnMut(&mut Map<String, Value>, &str),
) {
    let Value::Object(map) = schema else {
        return;
    };
    visit(map, pointer);
    for (key, child) in map.iter_mut() {
        let child_pointer = format!("{pointer}/{key}");
        let key = key.as_str();
        if SCHEMA_MAP_KEYWORDS.contains(&key) {
            if let Value::Object(entries) = child {
                for (name, sub) in entries.iter_mut() {
                    walk_schema(sub, &format!("{child_pointer}/{name}"), visit);
                }
            }
        } else if SCHEMA_KEYWORDS.contains(&key) {
            match child {
                // `items` in array form (draft 2019 and older).
                Value::Array(items) => {
                    for (i, sub) in items.iter_mut().enumerate() {
                        walk_schema(sub, &format!("{child_pointer}/{i}"), visit);
                    }
                }
                sub => walk_schema(sub, &child_pointer, visit),
            }
        } else if SCHEMA_ARRAY_KEYWORDS.contains(&key) {
            if let Value::Array(items) = child {
                for (i, sub) in items.iter_mut().enumerate() {
                    walk_schema(sub, &format!("{child_pointer}/{i}"), visit);
                }
            }
        }
    }
}

/// Walks every schema under a map of named schemas (`$defs`).
fn walk_defs(
    defs: &mut Value,
    pointer: &str,
    visit: &mut dyn FnMut(&mut Map<String, Value>, &str),
) {
    if let Value::Object(entries) = defs {
        for (name, schema) in entries.iter_mut() {
            walk_schema(schema, &format!("{pointer}/{name}"), visit);
        }
    }
}

/// Removes [`UNSUPPORTED_KEYWORDS`] from a schema object.
fn strip_unsupported(map: &mut Map<String, Value>, pointer: &str, removed: &mut Vec<String>) {
    for keyword in UNSUPPORTED_KEYWORDS {
        if map.remove(keyword).is_some() {
            removed.push(format!("{pointer}/{keyword}"));
        }
    }
}

/// Gives every `pattern` explicit search semantics: `P` becomes
/// `^[\s\S]*?(?:P)`.
///
/// JSON Schema patterns are unanchored searches. typify merges the patterns
/// of an `allOf` into lookaheads (`(?=A)(?=B)`) evaluated at the first
/// position where `A` matches, so an unanchored `B` (e.g. `MaskedSample`'s
/// "contains a `*`" rule) would only be tested at that position. Detecting
/// anchoring syntactically is error-prone (`^a|b` is not anchored), so every
/// pattern is wrapped: the wrapped pattern matches exactly the same strings
/// (without the `m` flag, `^` only matches at the start of the input), and
/// stays correct once merged.
fn wrap_pattern(map: &mut Map<String, Value>, pointer: &str, rewritten: &mut Vec<String>) {
    if let Some(Value::String(pattern)) = map.get_mut("pattern") {
        *pattern = format!("^[\\s\\S]*?(?:{pattern})");
        rewritten.push(format!("{pointer}/pattern"));
    }
}

/// Rewrites `const: X` as `enum: [X]` (same meaning in JSON Schema).
///
/// typify ignores `const` on a string property (it generates a free
/// `String`), so the `type` discriminator of each `Job` variant would accept
/// any value, e.g. `shell.exec`. A one-value `enum` becomes a one-variant
/// Rust enum, which serde enforces.
fn const_to_enum(map: &mut Map<String, Value>, pointer: &str, rewritten: &mut Vec<String>) {
    if !map.contains_key("enum") {
        if let Some(constant) = map.remove("const") {
            map.insert("enum".to_owned(), Value::Array(vec![constant]));
            rewritten.push(format!("{pointer}/const"));
        }
    }
}

/// Records `not` keywords: typify ignores them on string schemas, so they
/// are reported in the generated file header.
fn collect_not(map: &mut Map<String, Value>, pointer: &str, found: &mut Vec<String>) {
    if map.contains_key("not") {
        found.push(format!("{pointer}/not"));
    }
}

/// Rewrites `$ref: "#/components/schemas/X"` to `#/$defs/X`.
fn rewrite_ref(map: &mut Map<String, Value>, _pointer: &str) {
    if let Some(Value::String(target)) = map.get_mut("$ref") {
        if let Some(name) = target.strip_prefix(OPENAPI_REF_PREFIX) {
            *target = format!("{DEFS_REF_PREFIX}{name}");
        }
    }
}

/// Runs `pass` on every schema under `$defs` and returns the sorted
/// pointers it reports.
fn run_pass(
    schema: &mut Value,
    pass: fn(&mut Map<String, Value>, &str, &mut Vec<String>),
) -> Vec<String> {
    let mut found = Vec::new();
    if let Some(defs) = schema.get_mut("$defs") {
        walk_defs(defs, "#/$defs", &mut |map, pointer| {
            pass(map, pointer, &mut found);
        });
    }
    found.sort();
    found
}

/// Generates the Rust source of `databastion-protocol`'s `generated` module.
///
/// # Errors
/// If the document cannot be parsed or typify rejects a schema.
pub fn generate(openapi_yaml: &str) -> Result<String, CodegenError> {
    let mut schema = json_schema_from_openapi(openapi_yaml)?;
    let removed = run_pass(&mut schema, strip_unsupported);
    let negations = run_pass(&mut schema, collect_not);
    let constants = run_pass(&mut schema, const_to_enum);
    let wrapped = run_pass(&mut schema, wrap_pattern);
    let root: schemars::schema::RootSchema = serde_json::from_value(schema)?;
    let mut settings = typify::TypeSpaceSettings::default();
    settings.with_struct_builder(false);
    for (schema, rust_type) in REPLACEMENTS {
        settings.with_replacement(schema, rust_type, std::iter::empty());
    }
    let mut space = typify::TypeSpace::new(&settings);
    space.add_root_schema(root)?;
    let mut file: syn::File = syn::parse2(space.to_stream())?;
    strip_default_derives(&mut file);
    let mut unicode = UnicodePatterns { rewritten: 0 };
    syn::visit_mut::VisitMut::visit_file_mut(&mut unicode, &mut file);
    let mut out = String::from(HEADER);
    out.push_str(
        "//\n// Keywords not expressible by typify, removed before generation. Enforced by\n\
         // the console's Ajv validation; agent-side checks are a future step (P1-B, P2):\n",
    );
    for pointer in &removed {
        out.push_str("// - ");
        out.push_str(pointer);
        out.push('\n');
    }
    out.push_str("//\n// `not` keywords (not enforced by the generated types; same as above):\n");
    for pointer in &negations {
        out.push_str("// - ");
        out.push_str(pointer);
        out.push('\n');
    }
    out.push_str(&format!(
        "//\n// Patterns compiled with the ECMAScript `u` flag, as in Ajv: {}.\n",
        unicode.rewritten
    ));
    out.push_str("//\n// `const: X` rewritten as `enum: [X]` (typify ignores string `const`):\n");
    for pointer in &constants {
        out.push_str("// - ");
        out.push_str(pointer);
        out.push('\n');
    }
    out.push_str(&format!(
        "//\n// Patterns wrapped as `^[\\s\\S]*?(?:P)` (search semantics, same language): {}.\n",
        wrapped.len()
    ));
    out.push('\n');
    out.push_str(&prettyplease::unparse(&file));
    Ok(out)
}

/// Reads `openapi_path` and returns the generated source.
///
/// # Errors
/// On I/O or generation errors.
pub fn generate_from_file(openapi_path: &Path) -> Result<String, CodegenError> {
    let yaml = std::fs::read_to_string(openapi_path).map_err(|source| CodegenError::Io {
        path: openapi_path.to_owned(),
        source,
    })?;
    generate(&yaml)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn refs_are_rewritten_to_defs() {
        let yaml = r##"
components:
  schemas:
    A:
      type: object
      properties:
        b: { $ref: "#/components/schemas/B" }
    B: { type: string, maxLength: 3 }
"##;
        let schema = json_schema_from_openapi(yaml).unwrap();
        assert_eq!(
            schema["$defs"]["A"]["properties"]["b"]["$ref"],
            Value::String("#/$defs/B".to_owned())
        );
    }

    #[test]
    fn missing_schemas_is_an_error() {
        assert!(matches!(
            json_schema_from_openapi("openapi: 3.1.0\n"),
            Err(CodegenError::NoSchemas)
        ));
    }

    fn defs(value: Value) -> Value {
        serde_json::json!({ "$defs": value })
    }

    #[test]
    fn conditionals_are_stripped_and_reported() {
        let mut schema = defs(serde_json::json!({
            "A": { "type": "object", "if": {}, "then": {}, "properties": { "x": { "else": {} } } }
        }));
        let removed = run_pass(&mut schema, strip_unsupported);
        assert_eq!(
            removed,
            [
                "#/$defs/A/if",
                "#/$defs/A/properties/x/else",
                "#/$defs/A/then"
            ]
        );
        assert!(schema["$defs"]["A"].get("if").is_none());
    }

    #[test]
    fn every_pattern_gets_search_semantics() {
        let mut schema = defs(serde_json::json!({
            "A": { "pattern": "\\*", "allOf": [{ "pattern": "^x$" }, { "pattern": "^a|b" }] }
        }));
        let wrapped = run_pass(&mut schema, wrap_pattern);
        let a = &schema["$defs"]["A"];
        assert_eq!(a["pattern"], "^[\\s\\S]*?(?:\\*)");
        assert_eq!(a["allOf"][0]["pattern"], "^[\\s\\S]*?(?:^x$)");
        // `^a|b` is not anchored: `b` may match anywhere.
        assert_eq!(a["allOf"][1]["pattern"], "^[\\s\\S]*?(?:^a|b)");
        assert_eq!(wrapped.len(), 3);
    }

    #[test]
    fn walkers_only_touch_schema_keywords() {
        let mut schema = defs(serde_json::json!({
            "A": {
                "type": "object",
                "properties": {
                    // Property names that look like keywords.
                    "pattern": { "type": "string", "maxLength": 3 },
                    "const": { "type": "string", "const": "k" },
                    "if": { "type": "boolean" }
                },
                "default": { "pattern": "x", "const": 1, "if": true },
                "examples": [{ "pattern": "y", "const": 2 }],
                "enum": [{ "const": 3, "pattern": "z" }]
            }
        }));
        let original = schema.clone();
        let removed = run_pass(&mut schema, strip_unsupported);
        let wrapped = run_pass(&mut schema, wrap_pattern);
        let constants = run_pass(&mut schema, const_to_enum);
        assert!(removed.is_empty(), "{removed:?}");
        assert!(wrapped.is_empty(), "{wrapped:?}");
        assert_eq!(constants, ["#/$defs/A/properties/const/const"]);
        let a = &schema["$defs"]["A"];
        assert_eq!(
            a["properties"]["pattern"],
            original["$defs"]["A"]["properties"]["pattern"]
        );
        assert!(a["properties"].get("if").is_some());
        assert_eq!(a["default"], original["$defs"]["A"]["default"]);
        assert_eq!(a["examples"], original["$defs"]["A"]["examples"]);
        assert_eq!(a["enum"], original["$defs"]["A"]["enum"]);
    }

    #[test]
    fn patterns_get_the_unicode_flag() {
        let mut file: syn::File = syn::parse_quote! {
            fn f() { let _ = ::regress::Regex::new("^\\p{L}$").unwrap(); }
        };
        let mut unicode = UnicodePatterns { rewritten: 0 };
        syn::visit_mut::VisitMut::visit_file_mut(&mut unicode, &mut file);
        assert_eq!(unicode.rewritten, 1);
        let text = quote::quote!(#file).to_string();
        assert!(
            text.contains("with_flags (\"^\\\\p{L}$\" , \"u\")"),
            "{text}"
        );
    }

    #[test]
    fn const_becomes_one_value_enum() {
        let mut schema = defs(serde_json::json!({
            "A": { "properties": { "type": { "type": "string", "const": "x.y" } } }
        }));
        let rewritten = run_pass(&mut schema, const_to_enum);
        let t = &schema["$defs"]["A"]["properties"]["type"];
        assert_eq!(t["enum"], serde_json::json!(["x.y"]));
        assert!(t.get("const").is_none());
        assert_eq!(rewritten, ["#/$defs/A/properties/type/const"]);
    }

    #[test]
    fn default_is_stripped_from_data_structs_only() {
        let mut file: syn::File = syn::parse_quote! {
            #[derive(Clone, Default)]
            pub struct Data { pub a: u8 }
            #[derive(Clone, Default)]
            pub struct Empty {}
        };
        strip_default_derives(&mut file);
        let text = quote::quote!(#file).to_string();
        assert!(text.contains("derive (Clone)] pub struct Data"), "{text}");
        assert!(
            text.contains("derive (Clone , Default)] pub struct Empty"),
            "{text}"
        );
    }
}
