//! Hand-written wrappers for the `Uuid` and `UuidV7` schemas.
//! `databastion-protocol-codegen` substitutes them for the typify output,
//! which maps both to `uuid::Uuid` and so accepts uppercase and any version.
//! Here, `Deserialize` enforces the contract: canonical lowercase form, and
//! version 7 for `UuidV7`.

use std::fmt;

/// Error returned when a string is not a canonical UUID of the expected kind.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InvalidUuid {
    kind: &'static str,
}

impl fmt::Display for InvalidUuid {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "not a canonical lowercase {}", self.kind)
    }
}

impl std::error::Error for InvalidUuid {}

/// Parses a canonical lowercase hyphenated UUID.
fn parse_canonical(value: &str) -> Option<uuid::Uuid> {
    let parsed = uuid::Uuid::try_parse(value).ok()?;
    // Canonical form only: rejects uppercase, braces, URN and simple forms.
    (parsed.hyphenated().to_string() == value).then_some(parsed)
}

macro_rules! uuid_type {
    ($(#[$doc:meta])* $name:ident, $kind:literal, $check:expr) => {
        $(#[$doc])*
        #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
        pub struct $name(uuid::Uuid);

        impl $name {
            /// The underlying UUID.
            #[must_use]
            pub fn get(&self) -> uuid::Uuid {
                self.0
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                fmt::Display::fmt(&self.0.hyphenated(), f)
            }
        }

        impl TryFrom<uuid::Uuid> for $name {
            type Error = InvalidUuid;
            fn try_from(value: uuid::Uuid) -> Result<Self, Self::Error> {
                let check: fn(&uuid::Uuid) -> bool = $check;
                if check(&value) {
                    Ok(Self(value))
                } else {
                    Err(InvalidUuid { kind: $kind })
                }
            }
        }

        impl TryFrom<&str> for $name {
            type Error = InvalidUuid;
            fn try_from(value: &str) -> Result<Self, Self::Error> {
                parse_canonical(value)
                    .ok_or(InvalidUuid { kind: $kind })
                    .and_then(Self::try_from)
            }
        }

        impl serde::Serialize for $name {
            fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
                serializer.collect_str(&self.0.hyphenated())
            }
        }

        impl<'de> serde::Deserialize<'de> for $name {
            fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
                let value = String::deserialize(deserializer)?;
                Self::try_from(value.as_str()).map_err(serde::de::Error::custom)
            }
        }
    };
}

uuid_type!(
    /// Canonical lowercase UUID (schema `Uuid`).
    Uuid,
    "UUID",
    |_| true
);
uuid_type!(
    /// Canonical lowercase UUID version 7 (schema `UuidV7`), generated by the
    /// agent. Use [`new_batch_id`] for batch identifiers.
    UuidV7,
    "UUIDv7",
    |u| u.get_version_num() == 7 && u.get_variant() == uuid::Variant::RFC4122
);

/// A fresh, time-ordered batch identifier (`UuidV7`), as required for
/// `batch_id` in `FindingsBatch` / `EventsBatch` (idempotency key).
#[must_use]
pub fn new_batch_id() -> UuidV7 {
    UuidV7(uuid::Uuid::now_v7())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn batch_ids_are_valid_v7() {
        let id = new_batch_id();
        let text = serde_json::to_string(&id).unwrap();
        let back: UuidV7 = serde_json::from_str(&text).unwrap();
        assert_eq!(back, id);
        assert_ne!(new_batch_id(), id);
    }

    #[test]
    fn non_canonical_or_wrong_version_is_rejected() {
        let v7 = "01920f5f-0c30-7e6f-a043-2b3c4d5e6f70";
        assert!(UuidV7::try_from(v7).is_ok());
        assert!(Uuid::try_from(v7).is_ok());
        assert!(UuidV7::try_from("01920F5F-0C30-7E6F-A043-2B3C4D5E6F70").is_err());
        assert!(Uuid::try_from("01920F5F-0C30-7E6F-A043-2B3C4D5E6F70").is_err());
        assert!(UuidV7::try_from("01920f5f-0c30-4e6f-a043-2b3c4d5e6f70").is_err());
        assert!(Uuid::try_from("01920f5f0c307e6fa0432b3c4d5e6f70").is_err());
    }
}
