//! Agent <-> console protocol types (invariant I6).
//!
//! Every type in [`generated`] is generated by `databastion-protocol-codegen`
//! from `shared/protocol/openapi.yaml` (`components/schemas`) with typify, and
//! is **never** edited by hand. The `drift` test fails when the committed
//! file no longer matches the contract; regenerate with (from `agent/`):
//!
//! ```sh
//! cargo run -p databastion-protocol-codegen
//! ```
//!
//! # Security boundaries
//! - **Only the uplink** (crate-private in `databastion-core`) depends on this
//!   crate. Connectors must not (checked by
//!   `crates/agent/tests/architecture.rs`): they hand raw data to
//!   `classifiers::masking`, which is the only producer of uplink-bound
//!   values (I2, ADR-0003, ADR-0007).
//! - Conversions go one way: masking converts **to** these types, never the
//!   reverse. This crate does not depend on `databastion-classifiers`, so no
//!   `From`/`TryFrom` from a generated type into a masked type can exist here.
//! - Every generated struct has `#[serde(deny_unknown_fields)]`
//!   (`additionalProperties: false` in the schema). Structs that carry data
//!   do not derive `Default`.
//!
//! # What serde does not enforce
//! The generated types enforce types, `required`, closed objects, enums,
//! string `minLength` / `maxLength` and `pattern` (through `regress`, with
//! ECMAScript semantics), and the bounds typify maps to Rust integer types.
//! They do **not** enforce, among others: `if` / `then` / `else` (removed
//! before generation, listed in the header of `generated.rs`), `not`,
//! numeric `minimum` / `maximum` in general, `minItems` / `maxItems`,
//! `uniqueItems`, `maxProperties`, the lowercase / version pattern of
//! `Uuid` / `UuidV7` (mapped to [`uuid::Uuid`]) and `maxLength` of
//! `Timestamp` (mapped to `chrono`). The console's Ajv validation (strict,
//! unknown fields rejected) and the agent's own sanitizer before spooling
//! remain the enforcement points; `tests/fixtures.rs` lists every invalid
//! fixture that still deserializes, and why.
//!
//! Optional arrays are generated as `Vec` with `#[serde(default)]`: an
//! absent array and an empty array are the same value on the agent side.

#![forbid(unsafe_code)]

/// Types generated from `shared/protocol/openapi.yaml`. Do not edit.
///
/// Module-level allowances, for generated code only (the workspace lints
/// are not relaxed elsewhere):
/// - `clippy::unwrap_used`: typify compiles each schema `pattern` with
///   `Regex::new(..).unwrap()`; the patterns are constants, covered by the
///   fixture tests, so a failure is a build-time contract bug.
/// - `missing_docs`, `unreachable_pub`: schemas without `description`.
/// - `clippy::all`: style lints on generated code (e.g. `derivable_impls`,
///   `clone_on_copy`); correctness is covered by the fixture tests.
#[rustfmt::skip]
#[allow(
    missing_docs,
    unreachable_pub,
    clippy::all,
    clippy::unwrap_used,
    reason = "generated by typify; see the module documentation"
)]
pub mod generated;

pub use generated::*;
