"use client";

import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import { Input, Label } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import {
  channelErrorMessage,
  MAX_RECIPIENTS,
  TLS_MODES,
  type ChannelType,
  type EmailConfig,
  type WebhookConfig,
} from "@/lib/notification-model";

import { userApi } from "./client-api";

/**
 * Notification channels (admin). Secrets are write-only: the SMTP password is sent on create or
 * change and never shown again; a webhook signing secret is generated by the console and shown
 * once, in this component's state only (gone on navigation). Webhook URLs are shown by origin only.
 */

export interface ChannelItem {
  id: string;
  slug: string;
  type: ChannelType;
  enabled: boolean;
  systemAlerts: boolean;
  config: EmailConfig | WebhookConfig;
  secretSet: boolean;
}

const list = (v: string) => [...new Set(v.split(/[,\s]+/).map((s) => s.trim()).filter((s) => s !== ""))];

/**
 * Request body from the form values (`edit`: slug and type are fixed; an empty password keeps the
 * stored one; an empty webhook URL keeps the stored one).
 */
export function channelRequestBody(values: Record<string, string | boolean>, edit = false): Record<string, unknown> {
  const s = (k: string) => String(values[k] ?? "").trim();
  const type = s("type") === "webhook" ? "webhook" : "email";
  const body: Record<string, unknown> = {
    enabled: values.enabled === true || values.enabled === "on",
    system_alerts: values.system_alerts === true || values.system_alerts === "on",
  };
  if (!edit) {
    body.slug = s("slug");
    body.type = type;
  }
  if (type === "webhook") {
    if (!edit || s("url") !== "") body.config = { url: s("url") };
    return body;
  }
  const username = s("username");
  body.config = {
    host: s("host"),
    port: Number(s("port") || "587"),
    tls: s("tls") || "starttls",
    from: s("from"),
    recipients: list(s("recipients")),
    ...(username !== "" ? { username } : {}),
  };
  const password = String(values.password ?? "");
  if (password !== "") body.password = password;
  return body;
}

function SecretOnce({ secret, onDone }: { secret: string; onDone: () => void }) {
  const [copied, setCopied] = useState(false);
  return (
    <div role="status" className="flex flex-col gap-2 rounded-md border border-destructive/50 p-4">
      <p className="text-sm font-medium">
        Webhook signing secret: copy it now into the receiver, it is shown only once. The receiver checks the
        X-DataBastion-Signature header (t=&lt;unix time&gt;,v1=&lt;HMAC-SHA256 of &quot;t.body&quot;&gt;) and rejects old timestamps.
      </p>
      <code className="rounded bg-muted p-2 font-mono text-sm break-all select-all">{secret}</code>
      <div className="flex gap-2">
        <Button
          size="sm"
          onClick={async () => {
            await navigator.clipboard.writeText(secret);
            setCopied(true);
          }}
        >
          {copied ? "Copied" : "Copy"}
        </Button>
        <Button size="sm" variant="outline" onClick={onDone}>
          Done, hide it
        </Button>
      </div>
    </div>
  );
}

export function ChannelForm({ csrfToken, initial }: { csrfToken: string; initial?: ChannelItem }) {
  const router = useRouter();
  const [type, setType] = useState<ChannelType>(initial?.type ?? "email");
  const [message, setMessage] = useState<string | null>(null);
  const [secret, setSecret] = useState<string | null>(null);
  const edit = initial !== undefined;
  const email = initial?.type === "email" ? (initial.config as EmailConfig) : null;
  const id = (name: string) => `channel-${initial?.id ?? "new"}-${name}`;

  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const formEl = e.currentTarget;
    const form = new FormData(formEl);
    const values: Record<string, string | boolean> = Object.fromEntries([...form.entries()].map(([k, x]) => [k, String(x)]));
    values.type = type;
    values.enabled = form.get("enabled") === "on";
    values.system_alerts = form.get("system_alerts") === "on";
    setMessage(null);
    const res = await userApi(edit ? `/api/notification-channels/${initial.id}` : "/api/notification-channels", {
      method: edit ? "PATCH" : "POST",
      csrfToken,
      body: channelRequestBody(values, edit),
    }).catch(() => null);
    if (!res) {
      setMessage("The console is unreachable.");
      return;
    }
    if (!res.ok) {
      setMessage(channelErrorMessage(res.status, await res.json().catch(() => null)));
      return;
    }
    if (!edit) {
      const body = (await res.json()) as { signing_secret?: string };
      if (body.signing_secret) setSecret(body.signing_secret);
      formEl.reset();
    }
    setMessage("Saved.");
    router.refresh();
  }

  return (
    <div className="flex flex-col gap-4">
      <form onSubmit={submit} className="flex flex-col gap-4">
        {!edit && (
          <div className="grid gap-3 md:grid-cols-2">
            <div className="flex flex-col gap-1">
              <Label htmlFor={id("slug")}>Name (referenced by policies, e.g. secops-mail)</Label>
              <Input id={id("slug")} name="slug" required maxLength={63} autoComplete="off" pattern="[a-z0-9][a-z0-9_.\-]{0,62}" />
            </div>
            <div className="flex flex-col gap-1">
              <Label htmlFor={id("type")}>Type</Label>
              <select
                id={id("type")}
                value={type}
                onChange={(e) => setType(e.target.value === "webhook" ? "webhook" : "email")}
                className="h-9 rounded-md border border-input bg-transparent px-3 text-sm"
              >
                <option value="email">E-mail (SMTP)</option>
                <option value="webhook">Webhook (HMAC-signed HTTPS POST)</option>
              </select>
            </div>
          </div>
        )}
        {type === "email" ? (
          <div className="grid gap-3 md:grid-cols-3">
            <div className="flex flex-col gap-1">
              <Label htmlFor={id("host")}>SMTP host</Label>
              <Input id={id("host")} name="host" required maxLength={253} defaultValue={email?.host ?? ""} autoComplete="off" />
            </div>
            <div className="flex flex-col gap-1">
              <Label htmlFor={id("port")}>Port</Label>
              <Input id={id("port")} name="port" type="number" min={1} max={65535} required defaultValue={String(email?.port ?? 587)} />
            </div>
            <div className="flex flex-col gap-1">
              <Label htmlFor={id("tls")}>TLS</Label>
              <select id={id("tls")} name="tls" defaultValue={email?.tls ?? "starttls"} className="h-9 rounded-md border border-input bg-transparent px-3 text-sm">
                {TLS_MODES.map((m) => (
                  <option key={m} value={m}>
                    {m === "none" ? "none (loopback relay only)" : m}
                  </option>
                ))}
              </select>
            </div>
            <div className="flex flex-col gap-1">
              <Label htmlFor={id("from")}>Sender address</Label>
              <Input id={id("from")} name="from" type="email" required maxLength={254} defaultValue={email?.from ?? ""} autoComplete="off" />
            </div>
            <div className="flex flex-col gap-1 md:col-span-2">
              <Label htmlFor={id("recipients")}>Recipients (comma-separated, at most {MAX_RECIPIENTS})</Label>
              <Input id={id("recipients")} name="recipients" required maxLength={5200} defaultValue={email?.recipients.join(", ") ?? ""} autoComplete="off" />
            </div>
            <div className="flex flex-col gap-1">
              <Label htmlFor={id("username")}>SMTP user (optional)</Label>
              <Input id={id("username")} name="username" maxLength={256} defaultValue={email?.username ?? ""} autoComplete="off" />
            </div>
            <div className="flex flex-col gap-1">
              <Label htmlFor={id("password")}>
                SMTP password {edit && initial?.secretSet ? "(stored; leave empty to keep it)" : "(optional)"}
              </Label>
              <Input id={id("password")} name="password" type="password" maxLength={1024} autoComplete="new-password" />
            </div>
          </div>
        ) : (
          <div className="flex flex-col gap-1">
            <Label htmlFor={id("url")}>
              Webhook URL (https://){edit ? `: currently ${(initial?.config as WebhookConfig).origin}/…; leave empty to keep it` : ""}
            </Label>
            <Input id={id("url")} name="url" type="url" required={!edit} maxLength={2048} autoComplete="off" />
            <p className="text-xs text-muted-foreground">
              The receiver must escape the text fields it renders (HTML, Markdown, chat messages), the principal first:
              it is a database account name that any client of the database can choose.
            </p>
          </div>
        )}
        <div className="flex flex-wrap items-center gap-6">
          <label className="flex items-center gap-2 text-sm">
            <input name="enabled" type="checkbox" defaultChecked={initial?.enabled ?? true} className="size-4" />
            Enabled
          </label>
          <label className="flex items-center gap-2 text-sm">
            <input name="system_alerts" type="checkbox" defaultChecked={initial?.systemAlerts ?? false} className="size-4" />
            Also receive console alerts (silent agents, agent-integrity events, dropped batches)
          </label>
        </div>
        <div className="flex items-center gap-3">
          <Button type="submit">{edit ? "Save" : "Create channel"}</Button>
          {message && (
            <p role="status" className="text-sm text-muted-foreground">
              {message}
            </p>
          )}
        </div>
      </form>
      {secret && <SecretOnce secret={secret} onDone={() => setSecret(null)} />}
    </div>
  );
}

export function channelSummary(c: ChannelItem): string {
  if (c.type === "webhook") return `${(c.config as WebhookConfig).origin}/…`;
  const e = c.config as EmailConfig;
  return `${e.host}:${e.port} (${e.tls}) to ${e.recipients.length} recipient${e.recipients.length > 1 ? "s" : ""}${e.username ? ", SMTP auth" : ""}`;
}

function ChannelActions({ channel, csrfToken }: { channel: ChannelItem; csrfToken: string }) {
  const router = useRouter();
  const [message, setMessage] = useState<string | null>(null);
  const [secret, setSecret] = useState<string | null>(null);
  const [editing, setEditing] = useState(false);
  const call = async (path: string, method: string, body?: unknown) => {
    setMessage(null);
    const res = await userApi(path, { method, csrfToken, body }).catch(() => null);
    if (!res?.ok) setMessage(res ? channelErrorMessage(res.status, await res.json().catch(() => null)) : "The console is unreachable.");
    return res?.ok ? res : null;
  };
  const base = `/api/notification-channels/${channel.id}`;
  return (
    <div className="flex flex-col items-end gap-2">
      <div className="flex flex-wrap justify-end gap-2">
        <Button
          size="sm"
          variant="outline"
          onClick={async () => {
            if (await call(`${base}/test`, "POST")) setMessage("Test queued: see the deliveries below.");
            router.refresh();
          }}
        >
          Test
        </Button>
        <Button
          size="sm"
          variant="outline"
          onClick={async () => {
            await call(base, "PATCH", { enabled: !channel.enabled });
            router.refresh();
          }}
        >
          {channel.enabled ? "Disable" : "Enable"}
        </Button>
        <Button size="sm" variant="outline" onClick={() => setEditing((x) => !x)}>
          {editing ? "Close" : "Edit"}
        </Button>
        {channel.type === "webhook" && (
          <ConfirmDialog
            trigger="New secret"
            title="Replace the signing secret?"
            description="Deliveries are signed with the new secret at once: update the receiver right away."
            confirmLabel="Replace"
            onConfirm={async () => {
              const res = await call(`${base}/rotate-secret`, "POST");
              if (res) setSecret(((await res.json()) as { signing_secret: string }).signing_secret);
            }}
          />
        )}
        <ConfirmDialog
          trigger="Delete"
          title={`Delete the channel ${channel.slug}?`}
          description="Policies naming it keep the name (their notifications are then recorded as skipped). Past deliveries stay listed."
          confirmLabel="Delete"
          variant="destructive"
          onConfirm={async () => {
            await call(base, "DELETE");
            router.refresh();
          }}
        />
      </div>
      {message && (
        <p role="status" className="text-sm text-muted-foreground">
          {message}
        </p>
      )}
      {secret && <SecretOnce secret={secret} onDone={() => setSecret(null)} />}
      {editing && (
        <div className="w-full rounded-md border p-4 text-left">
          <ChannelForm csrfToken={csrfToken} initial={channel} />
        </div>
      )}
    </div>
  );
}

export function ChannelsTable({ channels, csrfToken }: { channels: ChannelItem[]; csrfToken: string }) {
  if (channels.length === 0) return <p className="text-sm text-muted-foreground">No channel yet.</p>;
  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead>Name</TableHead>
          <TableHead>Type</TableHead>
          <TableHead>Destination</TableHead>
          <TableHead>State</TableHead>
          <TableHead />
        </TableRow>
      </TableHeader>
      <TableBody>
        {channels.map((c) => (
          <TableRow key={c.id}>
            <TableCell className="font-medium break-all">{c.slug}</TableCell>
            <TableCell>{c.type}</TableCell>
            <TableCell className="break-all">{channelSummary(c)}</TableCell>
            <TableCell className="flex flex-wrap gap-1">
              <Badge variant={c.enabled ? "default" : "outline"}>{c.enabled ? "enabled" : "disabled"}</Badge>
              {c.systemAlerts && <Badge variant="secondary">console alerts</Badge>}
            </TableCell>
            <TableCell className="text-right">
              <ChannelActions channel={c} csrfToken={csrfToken} />
            </TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  );
}
