//! Built-in function names per server flavor and release series
//! (ADR-0045 decisions 7 and 8): the lists of `builtins/*.txt`, generated by
//! `builtins/extract.py` from the server parser sources and checked against
//! each engine-matrix image by the drift test (`it/builtins_it.rs`).
//!
//! The Audit analysis takes an unqualified call of any other name as a
//! possible stored or loadable function: a read of `*`, always reported,
//! never the agent's own (`classifiers::query::StatementInfo::unknown_call`).
//!
//! Which list ([`for_server`]): the list of the server's series; for a
//! series newer than the newest list of its flavor, that newest list
//! (logged once: names added since are reported, fail closed); for a series
//! older than the oldest list (end of life, ADR-0039 decision 1), the oldest
//! list; for a series between two lists (a short-term release), the names
//! on both, each in the stricter of its two forms. Never a union of lists:
//! a stored function named after a function of a later series would hide
//! behind it. Percona Server takes the MySQL list of its series. A name
//! built in only under MariaDB's `sql_mode=ORACLE` is on no list.

use std::sync::OnceLock;
use std::sync::atomic::{AtomicBool, Ordering};

use databastion_classifiers::query::{BuiltinFunctions, CallForm};

use crate::conn::Flavor;

/// How the server reads `name(` for a listed name (the `form` column of
/// the lists).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub(crate) enum Form {
    /// A keyword function of `lex.h`'s `sql_functions`: built in only
    /// unquoted with `(` right after it.
    KeywordAdjacent,
    /// Another keyword (a keyword function, or a word that is not a call
    /// there): built in unquoted, with or without whitespace before `(`.
    Keyword,
    /// A native function: built in plain, spaced or quoted.
    Native,
}

impl Form {
    fn accepts(self, form: CallForm) -> bool {
        matches!(
            (self, form),
            (Self::Native, _)
                | (Self::Keyword, CallForm::Plain | CallForm::Spaced)
                | (Self::KeywordAdjacent, CallForm::Plain)
        )
    }
}

/// One built-in name list.
#[derive(Debug)]
pub(crate) struct BuiltinList {
    pub(crate) flavor: Flavor,
    /// (major, minor) of the series; for a list made of two (an
    /// intersection), the lower one.
    pub(crate) series: (u32, u32),
    /// Lower-case names, sorted by bytes, with their forms.
    names: Vec<(Box<[u8]>, Form)>,
}

impl BuiltinList {
    fn parse(flavor: Flavor, series: (u32, u32), text: &str) -> Self {
        let mut names: Vec<(Box<[u8]>, Form)> = text
            .lines()
            .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
            .filter_map(|l| {
                let (name, form) = l.split_once(' ')?;
                let form = match form.trim() {
                    "n" => Form::Native,
                    "k" => Form::Keyword,
                    "s" => Form::KeywordAdjacent,
                    _ => return None,
                };
                Some((
                    name.to_ascii_lowercase().into_bytes().into_boxed_slice(),
                    form,
                ))
            })
            .collect();
        names.sort();
        names.dedup_by(|a, b| a.0 == b.0);
        Self {
            flavor,
            series,
            names,
        }
    }

    /// The names on both lists, each in the stricter form.
    fn intersection(a: &Self, b: &Self) -> Self {
        let names = a
            .names
            .iter()
            .filter_map(|(n, f)| b.form(n).map(|g| (n.clone(), (*f).min(g))))
            .collect();
        Self {
            flavor: a.flavor,
            series: a.series.min(b.series),
            names,
        }
    }

    /// The form of a listed name (`name` in any case, compared in place).
    pub(crate) fn form(&self, name: &[u8]) -> Option<Form> {
        self.names
            .binary_search_by(|(n, _)| {
                n.iter()
                    .copied()
                    .cmp(name.iter().map(u8::to_ascii_lowercase))
            })
            .ok()
            .map(|i| self.names[i].1)
    }

    /// Every listed name with its form (drift test).
    #[cfg(test)]
    pub(crate) fn names(&self) -> impl Iterator<Item = (&str, Form)> {
        self.names
            .iter()
            .map(|(n, f)| (std::str::from_utf8(n).unwrap_or(""), *f))
    }

    #[cfg(test)]
    pub(crate) fn len(&self) -> usize {
        self.names.len()
    }
}

impl BuiltinFunctions for BuiltinList {
    fn is_builtin(&self, name: &[u8], form: CallForm) -> bool {
        // Built-in names are ASCII; anything else is not one.
        name.is_ascii() && self.form(name).is_some_and(|f| f.accepts(form))
    }
}

/// The committed lists: (flavor, series, text).
const LISTS: [(Flavor, (u32, u32), &str); 6] = [
    (
        Flavor::Mysql,
        (8, 0),
        include_str!("../builtins/mysql-8.0.txt"),
    ),
    (
        Flavor::Mysql,
        (8, 4),
        include_str!("../builtins/mysql-8.4.txt"),
    ),
    (
        Flavor::Mysql,
        (9, 7),
        include_str!("../builtins/mysql-9.7.txt"),
    ),
    (
        Flavor::Mariadb,
        (10, 11),
        include_str!("../builtins/mariadb-10.11.txt"),
    ),
    (
        Flavor::Mariadb,
        (11, 4),
        include_str!("../builtins/mariadb-11.4.txt"),
    ),
    (
        Flavor::Mariadb,
        (11, 8),
        include_str!("../builtins/mariadb-11.8.txt"),
    ),
];

/// Every committed list, parsed once.
pub(crate) fn lists() -> &'static [BuiltinList] {
    static PARSED: OnceLock<Vec<BuiltinList>> = OnceLock::new();
    PARSED.get_or_init(|| {
        LISTS
            .iter()
            .map(|(f, s, t)| BuiltinList::parse(*f, *s, t))
            .collect()
    })
}

/// The list of a flavor and series, if there is one.
#[cfg(test)]
pub(crate) fn list(flavor: Flavor, series: (u32, u32)) -> Option<&'static BuiltinList> {
    lists()
        .iter()
        .find(|l| l.flavor == flavor && l.series == series)
}

/// The intersections of two neighbouring lists of a flavor, for the
/// series between them, built once.
fn between(lower: &'static BuiltinList, upper: &'static BuiltinList) -> &'static BuiltinList {
    static BUILT: OnceLock<Vec<(usize, usize, BuiltinList)>> = OnceLock::new();
    let all = lists();
    let index = |l: &BuiltinList| all.iter().position(|x| std::ptr::eq(x, l)).unwrap_or(0);
    let built = BUILT.get_or_init(|| {
        all.iter()
            .enumerate()
            .flat_map(|(i, a)| {
                all.iter()
                    .enumerate()
                    .filter(move |(_, b)| b.flavor == a.flavor && b.series > a.series)
                    .map(move |(j, b)| (i, j, BuiltinList::intersection(a, b)))
            })
            .collect()
    });
    let (i, j) = (index(lower), index(upper));
    built
        .iter()
        .find(|(a, b, _)| *a == i && *b == j)
        .map_or(lower, |(_, _, l)| l)
}

/// The names built in on every listed series of every flavor: for an
/// event builder whose server is not known (tests, a stream built before
/// its prerequisites).
pub(crate) fn any_server() -> &'static BuiltinList {
    static ALL: OnceLock<BuiltinList> = OnceLock::new();
    ALL.get_or_init(|| {
        let all = lists();
        all.iter()
            .skip(1)
            .fold(BuiltinList::intersection(&all[0], &all[0]), |acc, l| {
                BuiltinList::intersection(&acc, l)
            })
    })
}

/// The list for a server of `flavor` at `version` (see the module
/// documentation).
pub(crate) fn for_server(flavor: Flavor, version: (u32, u32, u32)) -> &'static BuiltinList {
    static NEWER_LOGGED: [AtomicBool; 2] = [AtomicBool::new(false), AtomicBool::new(false)];
    let series = (version.0, version.1);
    let mut of_flavor: Vec<&'static BuiltinList> =
        lists().iter().filter(|l| l.flavor == flavor).collect();
    of_flavor.sort_by_key(|l| l.series);
    let (Some(oldest), Some(newest)) = (of_flavor.first().copied(), of_flavor.last().copied())
    else {
        return any_server();
    };
    if let Some(l) = of_flavor.iter().find(|l| l.series == series) {
        return l;
    }
    if series > newest.series {
        let logged = &NEWER_LOGGED[usize::from(flavor == Flavor::Mariadb)];
        if !logged.swap(true, Ordering::Relaxed) {
            tracing::info!(
                flavor = flavor.as_str(),
                server = %format!("{}.{}", series.0, series.1),
                list = %format!("{}.{}", newest.series.0, newest.series.1),
                "no built-in function list for this server series: the newest list of its \
                 flavor is used, and calls of functions added since are reported as reads of `*`"
            );
        }
        return newest;
    }
    if series < oldest.series {
        return oldest;
    }
    let lower = of_flavor
        .iter()
        .rev()
        .find(|l| l.series < series)
        .copied()
        .unwrap_or(oldest);
    let upper = of_flavor
        .iter()
        .find(|l| l.series > series)
        .copied()
        .unwrap_or(newest);
    between(lower, upper)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_list_parses_sorted_and_records_its_source() {
        for (flavor, series, text) in LISTS {
            let l = list(flavor, series).unwrap();
            assert!(l.len() > 400, "{flavor:?} {series:?}: {}", l.len());
            assert!(
                text.lines().any(|x| x.starts_with("# source: ")
                    && x.contains(&format!("{}.{}", series.0, series.1))),
                "{flavor:?} {series:?}"
            );
            let body: Vec<&str> = text.lines().filter(|x| !x.starts_with('#')).collect();
            let mut sorted = body.clone();
            sorted.sort_unstable();
            assert_eq!(body, sorted, "{flavor:?} {series:?}: not sorted");
            assert_eq!(body.len(), l.len(), "{flavor:?} {series:?}: duplicates");
            for line in body {
                let (name, form) = line.split_once(' ').unwrap();
                assert!(
                    name.bytes()
                        .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'_'),
                    "{line}"
                );
                assert!(matches!(form, "n" | "k" | "s"), "{line}");
            }
        }
    }

    #[test]
    fn forms_decide_by_quoting_and_spacing() {
        let l = list(Flavor::Mysql, (8, 4)).unwrap();
        for (name, plain, spaced, quoted) in [
            ("concat", true, true, true),
            ("CONCAT", true, true, true),
            ("now", true, false, false),
            ("count", true, false, false),
            ("if", true, true, false),
            ("in", true, true, false),
            ("get_customer_email", false, false, false),
            ("conca", false, false, false),
            ("concat ", false, false, false),
            ("\u{e9}", false, false, false),
        ] {
            let n = name.as_bytes();
            assert_eq!(l.is_builtin(n, CallForm::Plain), plain, "{name}");
            assert_eq!(l.is_builtin(n, CallForm::Spaced), spaced, "{name}");
            assert_eq!(l.is_builtin(n, CallForm::Quoted), quoted, "{name}");
        }
    }

    /// ADR-0045 decision 8.
    #[test]
    fn the_list_follows_the_series() {
        let s = |l: &BuiltinList| (l.flavor, l.series);
        assert_eq!(
            s(for_server(Flavor::Mysql, (8, 0, 46))),
            (Flavor::Mysql, (8, 0))
        );
        assert_eq!(
            s(for_server(Flavor::Mysql, (8, 0, 11))),
            (Flavor::Mysql, (8, 0))
        );
        assert_eq!(
            s(for_server(Flavor::Mysql, (8, 4, 2))),
            (Flavor::Mysql, (8, 4))
        );
        assert_eq!(
            s(for_server(Flavor::Mysql, (9, 7, 2))),
            (Flavor::Mysql, (9, 7))
        );
        assert_eq!(
            s(for_server(Flavor::Mariadb, (11, 4, 13))),
            (Flavor::Mariadb, (11, 4))
        );
        // Newer: the newest list of the flavor.
        assert_eq!(
            s(for_server(Flavor::Mysql, (10, 0, 0))),
            (Flavor::Mysql, (9, 7))
        );
        assert_eq!(
            s(for_server(Flavor::Mariadb, (12, 1, 0))),
            (Flavor::Mariadb, (11, 8))
        );
        // Older: the oldest.
        assert_eq!(
            s(for_server(Flavor::Mysql, (5, 7, 44))),
            (Flavor::Mysql, (8, 0))
        );
        assert_eq!(
            s(for_server(Flavor::Mariadb, (10, 6, 20))),
            (Flavor::Mariadb, (10, 11))
        );
        // Between two lists: the names on both, never a union.
        let mid = for_server(Flavor::Mysql, (9, 1, 0));
        assert_eq!(s(mid), (Flavor::Mysql, (8, 4)));
        let lower = list(Flavor::Mysql, (8, 4)).unwrap();
        let upper = list(Flavor::Mysql, (9, 7)).unwrap();
        assert!(mid.len() <= lower.len().min(upper.len()));
        for (name, form) in mid.names() {
            let n = name.as_bytes();
            assert!(lower.form(n).is_some_and(|f| f >= form), "{name}");
            assert!(upper.form(n).is_some_and(|f| f >= form), "{name}");
        }
        // MD5 and SHA1 are not built in on MySQL 9.7 (the drift test).
        assert!(lower.form(b"md5").is_some() && upper.form(b"md5").is_none());
        assert!(mid.form(b"md5").is_none());
        // Every list differs from a union: a later series' function is
        // not built in on an earlier one.
        let vector = b"vector_dim";
        assert!(upper.form(vector).is_some());
        assert!(list(Flavor::Mysql, (8, 0)).unwrap().form(vector).is_none());
        // MariaDB: names built in only under `sql_mode=ORACLE`, and
        // unreserved keywords that are not functions, are on no list.
        for l in lists().iter().filter(|l| l.flavor == Flavor::Mariadb) {
            for name in ["against", "columns", "json_table", "point"] {
                assert!(l.form(name.as_bytes()).is_none(), "{name}");
            }
        }
        let any = any_server();
        assert!(any.form(b"now").is_some() && any.form(b"md5").is_none());
    }
}
